### ISSUE TITLE
ImportError: cannot import name 'f' from 'pandas.core.resample' 

### ISSUE THREAD

**Issue by heya5** [RUCAIBox/TextBox#288]
Hello, 

Is that a pandas version problem? which pandas version does TextBox need?
python: 3.8.15
pandas: 1.5.2

```
(textbox) hy@xxx:~/TextBox$ python run_textbox.py --model_path=facebook/bart-base
Traceback (most recent call last):
  File "run_textbox.py", line 2, in <module>
    from textbox import run_textbox
  File "/home/hy/TextBox/textbox/__init__.py", line 8, in <module>
    from textbox.quick_start.hyper_tuning import run_hyper
  File "/home/hy/TextBox/textbox/quick_start/hyper_tuning.py", line 14, in <module>
    from .experiment import Experiment
  File "/home/hy/TextBox/textbox/quick_start/experiment.py", line 12, in <module>
    from ..trainer.trainer import Trainer
  File "/home/hy/TextBox/textbox/trainer/__init__.py", line 1, in <module>
    from textbox.trainer.trainer import Trainer
  File "/home/hy/TextBox/textbox/trainer/trainer.py", line 16, in <module>
    from textbox.utils.dashboard import get_dashboard, Timestamp, EpochTracker
  File "/home/hy/TextBox/textbox/utils/dashboard.py", line 13, in <module>
    from pandas.core.resample import f
ImportError: cannot import name 'f' from 'pandas.core.resample' 
```

**Comment by StevenTang1998** [comment]
You can delete line 13 `from pandas.core.resample import f`.
We will check it in detail tomorrow. Thanks for your reporting!

**Comment by StevenTang1998** [comment]
We have fixed this issue in the latest pr. Thanks!
