### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6797: character maps to <undefined>

### ISSUE THREAD

**Issue by GeneralDarwinz** [RUCAIBox/TextBox#324]
Hey there,

Thanks for the amazing work.

Actually I face some codec problem when loading an example "python run_textbox.py --model=BART --dataset=samsum --model_path=facebook/bart-base"

`Traceback (most recent call last):
  File "run_textbox.py", line 12, in <module>
    run_textbox(model=args.model, dataset=args.dataset, config_file_list=args.config_files, config_dict={})
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\quick_start\quick_start.py", line 20, in run_textbox
    experiment = Experiment(model, dataset, config_file_list, config_dict)
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\quick_start\experiment.py", line 52, in __init__
    self._init_data(self.get_config(), self.accelerator)
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\quick_start\experiment.py", line 78, in _init_data
    train_data, valid_data, test_data = data_preparation(config, tokenizer)
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\data\utils.py", line 23, in data_preparation
    train_dataset = AbstractDataset(config, 'train')
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\data\abstract_dataset.py", line 25, in __init__
    self.source_text = load_data(source_filename, max_length=self.quick_test)
  File "C:\Users\korn2\Desktop\TextBox-2.0.0\textbox\data\misc.py", line 25, in load_data
    for line in fin:
  File "C:\Users\korn2\anaconda3\envs\TextBox\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6797: character maps to <undefined>`

any ideas ?

Cheers,
Kevin L

**Comment by StevenTang1998** [comment]
Hi Kevin,

I think it is due to the slightly different encoding logic of Windows, and we do not conduct tests of our TextBox on Windows. It is recommended to use TextBox on Ubuntu.

Best,
Tianyi

**Comment by StevenTang1998** [comment]
I will close the issue. If you still have a question, you can reopen it.
