### ISSUE TITLE
[🐛BUG] generation的时候无法生成txt。

### ISSUE THREAD

**Issue by 01vanilla** [RUCAIBox/TextBox#345]
**描述这个 bug**
我在使用T5对samsum进行训练时，发现tmp中model和system文件夹都没有生成对应的txt文件，以致报错

**如何复现**
python run_textbox.py     --model=T5     --model_path=t5-small     --dataset=samsum

**日志**
Trainable parameters: 60492288
21 Apr 13:23    INFO ====== Start training ======
train    1: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [02:45<00:00,  2.15s/step, loss=3.77]
21 Apr 13:26    INFO Train epoch  1 [time: 165.30s, loss: 3.77]
generating: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52/52 [00:27<00:00,  1.92it/s]
2023-04-21 13:26:48,490 [MainThread  ] [INFO ]  Set ROUGE home directory to /root/.files2rouge.
21 Apr 13:26    INFO Set ROUGE home directory to /root/.files2rouge.
2023-04-21 13:26:48,491 [MainThread  ] [INFO ]  Writing summaries.
21 Apr 13:26    INFO Writing summaries.
2023-04-21 13:26:48,491 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /tmp/tmpxmwjid7r/system and model files to /tmp/tmpxmwjid7r/model.
21 Apr 13:26    INFO Processing summaries. Saving system files to /tmp/tmpxmwjid7r/system and model files to /tmp/tmpxmwjid7r/model.
2023-04-21 13:26:48,491 [MainThread  ] [INFO ]  Processing files in /tmp/tmpk9_qxsya/system.
21 Apr 13:26    INFO Processing files in /tmp/tmpk9_qxsya/system.
2023-04-21 13:26:48,492 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpxmwjid7r/system.
21 Apr 13:26    INFO Saved processed files to /tmp/tmpxmwjid7r/system.
2023-04-21 13:26:48,492 [MainThread  ] [INFO ]  Processing files in /tmp/tmpk9_qxsya/model.
21 Apr 13:26    INFO Processing files in /tmp/tmpk9_qxsya/model.
2023-04-21 13:26:48,492 [MainThread  ] [INFO ]  Saved processed files to /tmp/tmpxmwjid7r/model.
21 Apr 13:26    INFO Saved processed files to /tmp/tmpxmwjid7r/model.
21 Apr 13:26    ERROR Traceback (most recent call last):
  File "/hy-tmp/TextBox/textbox/utils/dashboard.py", line 311, in new_experiment
    yield True
  File "/hy-tmp/TextBox/textbox/quick_start/experiment.py", line 140, in run
    self._do_train_and_valid()
  File "/hy-tmp/TextBox/textbox/quick_start/experiment.py", line 115, in _do_train_and_valid
    self.valid_result = self.trainer.fit(train_data, valid_data)
  File "/hy-tmp/TextBox/textbox/trainer/trainer.py", line 456, in fit
    self.stopped |= self._valid(valid_data, 'epoch')
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/hy-tmp/TextBox/textbox/trainer/trainer.py", line 294, in _valid
    valid_results = self.evaluate(valid_data, is_valid=True)
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/hy-tmp/TextBox/textbox/trainer/trainer.py", line 568, in evaluate
    result = self.evaluator.evaluate(generate_corpus, reference_dataset)
  File "/hy-tmp/TextBox/textbox/evaluator/base_evaluator.py", line 156, in evaluate
    metric_result = evaluator.evaluate(generate_corpus, reference_corpus, avg=avg)
  File "/hy-tmp/TextBox/textbox/evaluator/abstract_evaluator.py", line 31, in evaluate
    metric_dict = self._calc_metrics_info(generate_corpus=generate_corpus, reference_corpus=reference_corpus)
  File "/hy-tmp/TextBox/textbox/evaluator/rouge_evaluator.py", line 58, in _calc_metrics_info
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/pyrouge-0.1.3-py3.8.egg/pyrouge/Rouge155.py", line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/pyrouge-0.1.3-py3.8.egg/pyrouge/Rouge155.py", line 334, in evaluate
    self.write_config(system_id=system_id)
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/pyrouge-0.1.3-py3.8.egg/pyrouge/Rouge155.py", line 315, in write_config
    Rouge155.write_config_static(
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/pyrouge-0.1.3-py3.8.egg/pyrouge/Rouge155.py", line 277, in write_config_static
    raise Exception(
Exception: Did not find any files matching the pattern s.(\d+).txt in the system summaries directory /tmp/tmpxmwjid7r/system.

**Comment by StevenTang1998** [comment]
请问这个bug能在不同的服务器稳定复现吗？我这边无法复现出来。猜测是与服务器的tmp清理机制相关。

**Comment by StevenTang1998** [comment]
如果有问题欢迎继续提问
