### ISSUE TITLE
[🐛BUG] 想请问一下ckpt文件是如何生成的

### ISSUE THREAD

**Issue by Arthas183** [RUCAIBox/TextBox#358]
**描述这个 bug**
换了一个yelp数据集，尝试执行
python run_textbox.py --model=PTG --dataset=task927_yelp_negative_to_positive_style_transfer --model_path=facebook/bart-large
会报错，缺失task927_yelp_negative_to_positive_style_transfer.ckpt文件。
**如何复现**
python run_textbox.py --model=PTG --dataset=task927_yelp_negative_to_positive_style_transfer --model_path=facebook/bart-large
**日志**
10 Jun 23:30    ERROR Traceback (most recent call last):
  File "/root/TextBox/textbox/utils/dashboard.py", line 311, in new_experiment
    yield True
  File "/root/TextBox/textbox/quick_start/experiment.py", line 139, in run
    self._on_experiment_start(extended_config)
  File "/root/TextBox/textbox/quick_start/experiment.py", line 96, in _on_experiment_start
    self.trainer: Trainer = get_trainer(config['model'])(config, self.model, self.accelerator)
  File "/root/TextBox/textbox/trainer/trainer.py", line 105, in __init__
    self.evaluator = BaseEvaluator(config, self.config["metrics"])
  File "/root/TextBox/textbox/evaluator/base_evaluator.py", line 120, in __init__
    evaluator = StyleEvaluator(self.config)
  File "/root/TextBox/textbox/evaluator/style_evaluator.py", line 63, in __init__
    self.model.load_state_dict(torch.load(f'textbox/evaluator/utils/{config["dataset"]}.ckpt'))
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/miniconda3/envs/TextBox/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'textbox/evaluator/utils/task927_yelp_negative_to_positive_style_transfer.ckpt'

**Comment by StevenTang1998** [comment]
Sorry for late response. We used the ckpts provided at https://github.com/laihuiyuan/pre-trained-formality-transfer/tree/main/checkpoints. They are classifier models based on CNN.

**Comment by Arthas183** [comment]
好的谢谢您了。方便加一个微信或者邮箱吗？我是一名研二学生，想跟您请教一下关于这篇论文的一些细节。我最近一直在用您这边的TextBox，希望在毕业设计里面使用一下这个平台来跑实验，但有些地方的代码理解的不是很到位。刚看了您的twitter不能给发私信，所以希望您能加一个微信或者邮箱方便请教，可以吗？谢谢您！

**Comment by StevenTang1998** [comment]
好的，我的邮箱是1020139164@qq.com

**Comment by StevenTang1998** [comment]
好的，在我们的论文你可以找我的邮箱~
